name: "Workflow-history"
on: 
  workflow_dispatch:

jobs:
  check_workflow_runs:
    name: Check if workflows run
    runs-on: ubuntu-latest
    steps:
      - name: Get current workflow ID
        id: get_workflow_id
        run: |
          workflow_id=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | \
            jq ".workflows[] | select(.name==\"${{ github.workflow }}\") | .id")

          echo "Workflow ID: $workflow_id"
          echo "workflow_id=$workflow_id" >> $GITHUB_OUTPUT
          
      - name: Wait until previous workflow runs complete
        id: wait_for_completion
        run: |
          while true; do
            response=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ steps.get_workflow_id.outputs.workflow_id }}/runs?branch=main&status=in_progress")
            
            runs=$(echo "$response" | jq '.total_count')

            if [ "$runs" -eq 0 ]; then
              echo "No in-progress runs found."
              break
            else
              echo "Found $runs in-progress runs. Waiting..."
              sleep 60
            fi
          done
      - uses: actions/checkout@v4
      
      - name: Run the test powershell script
        shell: pwsh
        run: |
          .\Scripts\test.ps1
